<?php

/**
 * @file
 * Contains project_utilities.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\field\Entity\FieldConfig;
use Drupal\Core\Url;


/**
 * Implements hook_form_alter().
 */
function project_utilities_form_alter(&$form, &$form_state, $form_id) {

  // Kill the redundant help message under the login username/password fields.
  if ($form_id == 'user_login_form') {
    unset($form['name']['#description']);
    unset($form['pass']['#description']);
  }

  // Hide access to fields since Field Permissions is either overkill or doesn't do the job
  $user_role = \Drupal::currentUser()->getRoles();
  $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  $uid = $user->get('uid')->value;
  if (($uid == 1) || (in_array('developer', $user_role))) {
    $form['field_related_view']['#access'] = TRUE;
  }
  else {
    $form['field_related_view']['#access'] = FALSE;
  }

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function project_utilities_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'project_utilities_user_login_form_submit';
}

/**
 * Custom submit handler for the login form.
 */
function project_utilities_user_login_form_submit($form, FormStateInterface $form_state) {
  $url = Url::fromRoute('<front>');
  $form_state->setRedirectUrl($url);
}
