<?php

/**
 * @file
 * Contains custom_paragraphs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_help().
 */
function custom_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_paragraphs module.
    case 'help.page.custom_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom paragraph bundles with default styles and behaviors') . '</p>';
      $output .= '<p><a href="/admin/config/custom-paragraphs/style-options">' . t('Config options for fields') . '</a></p>';
      return $output;

  }
}
